server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: myJwtSecretKey
  expiration: 3600000
